# Generated by Django 5.1.1 on 2024-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0002_delete_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Popular_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='newarrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='offerproducts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='trending_one',
            field=models.BooleanField(default=False),
        ),
    ]
