# Generated by Django 5.1.1 on 2024-11-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0002_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offerprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
