# Generated by Django 5.1.1 on 2024-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0003_category_category_image_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='CaruoselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('carusoel_image', models.ImageField(blank=True, null=True, upload_to='caurose_image/')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='isofferproduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='ispopular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image/'),
        ),
    ]
