# Generated by Django 5.1.1 on 2024-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0004_bannerimage_caruoselitem_products_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruoselitem',
            name='carusoel_image',
            field=models.ImageField(upload_to='carousel_images/'),
        ),
    ]
