# Generated by Django 5.1.1 on 2024-11-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0004_products_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='price',
        ),
    ]
