# Generated by Django 5.1.1 on 2024-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0005_alter_caruoselitem_carusoel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='CaruoselItem',
        ),
    ]
