# Generated by Django 5.1.1 on 2024-11-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0007_rename_iamge_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Popular_products',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='isofferproduct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='newarrival',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='trending_one',
            field=models.BooleanField(),
        ),
    ]
