# Generated by Django 5.1.1 on 2024-11-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantities',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_weights',
        ),
    ]
