# Generated by Django 5.1.1 on 2024-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0011_remove_order_quantities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
