# Generated by Django 5.1.1 on 2025-01-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.BigIntegerField(max_length=15),
        ),
    ]
