# Generated by Django 5.1.1 on 2025-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0002_alter_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.BigIntegerField(),
        ),
    ]
