# Generated by Django 5.1.1 on 2025-01-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0006_alter_userprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
